apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  namespace: zhoufr
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: 10.16.1.254/kubeguide/guestbook-php-frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80

